spring.application.name=back

api.security.token.secret=minha-chave-muito-secreta-e-ultra-segura-com-mais-de-32-caracteres

# spring.datasource.url=jdbc:h2:file:./data/spring-security
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# # spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/crm_corretora
spring.datasource.username=postgres
spring.datasource.password=postgre

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true